# Generated by Django 4.2.7 on 2023-11-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_image_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="Add Profile Bio Here.", max_length=500),
        ),
    ]
